CREATE TABLE users
(
    id INT AUTO_INCREMENT UNSIGNED PRIMARY KEY,
    name VARCHAR(191),
    password VARCHAR(191)  NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE posts
(
    id INT AUTO_INCREMENT UNSIGNED PRIMARY KEY,
    user_id INT NOT NULL,
    img_name VARCHAR(191),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE comments
(
    id INT AUTO_INCREMENT UNSIGNED PRIMARY KEY,
    post_id INT NOT NULL,
    user_id INT NOT NULL,
    comment_body VARCHAR(256),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);