CREATE TABLE users
(
    id INT AUTO_INCREMENT PRIMARY KEY
    name VARCHAR(255),
    password VARCHAR(255)  NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE posts
(
    id INT AUTO_INCREMENT PRIMARY KEY
    user_id INT NOT NULL,
    img_name VARCHAR(255),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE comments
(
    id INT AUTO_INCREMENT PRIMARY KEY
    post_id INT NOT NULL,
    user_id INT NOT NULL,
    comment_body VARCHAR(255),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);